#spring.port=8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 6
          max-interval: 10s
          multiplier: 1
  data:
    cassandra:
#      keyspace-name: game
      keyspace: game
      contact-points: 127.0.0.1
      port: 9042
      schemaAction: CREATE_IF_NOT_EXISTS
jokenpo:
  game:
    routingkey: jokenpo.game
    queue: jokenpo.game.queue
    exchange: jokenpo.game.exchange
    dlq-routingkey: jokenpo.game-dlq
    dlq-exchange: jokenpo.game.exchange
    dlq-queue: jokenpo.game.queue-dlq



#spring.data.neo4j.username=neo4j
#spring.data.neo4j.password=secret